

import * as FiIcons from "react-icons/fi";
import React from "react";

export const MiddleData = [
    {
        id: 11,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-1.webp",

    },
    {
        id: 12,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-2.webp",
    },
    {
        id: 13,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-3.webp",
    },
    {
        id: 14,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-4.webp",
    },
    {
        id: 15,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-5.webp",
    },
    {
        id: 16,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-6.webp",
    },
    {
        id: 17,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-7.webp",
    },
    {
        id: 18,
        title: "Максим Максимова",
        path: "/Avatar",
        icon_instagram: <FiIcons.FiInstagram/>,
        icon_youtube: <FiIcons.FiYoutube/>,
        icon_facebook: <FiIcons.FiFacebook/>,
        number_instagram: "134 000 +",
        number_youtube: "3 160 000 +",
        number_facebook: "128 000 +",
        pic_avatar: "../../img/pic-8.webp",
    },
]